---
- name: Unbound control setup
  command: "{{ 'unbound-control-setup -d ' + hostvars[inventory_hostname]['unbound_control_setup_dest'] }}"
  when:
  - "hostvars[inventory_hostname]['unbound_control_setup'] is defined"
  - "(hostvars[inventory_hostname]['unbound_control_setup'] == 'always' or (hostvars[inventory_hostname]['unbound_control_setup'] == 'true' and vars['find_result']['files'] | length == 0))"
- name: Generate unbound.conf
  template:
    src: "unbound.j2"
    dest: "{{ hostvars[inventory_hostname]['unbound_conf_dest'] + '/' + hostvars[inventory_hostname]['unbound_conf'] }}"
    owner: "root"
    group: "root"
    mode: "0644"
  register: "unbound_deploy_result"
  notify:
  - 'Validate unbound configuration'
