---
- name: unbound | Download root hints
  ansible.builtin.get_url:
    url: "{{ hostvars[inventory_hostname]['unbound_root_hints_src'] }}"
    dest: "{{ hostvars[inventory_hostname]['unbound_root_hints_dest'] }}"
    mode: "0644"
    owner: "root"
    group: "root"
  when:
  - "hostvars[inventory_hostname]['unbound_download_root_hints'] == 'true'"
  - "unbound_root_hints_stat.stat.exists == False"
- name: unbound | Download root hints
  ansible.builtin.get_url:
    url: "{{ hostvars[inventory_hostname]['unbound_root_hints_src'] }}"
    dest: "{{ hostvars[inventory_hostname]['unbound_root_hints_dest'] }}"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "yes"
  when:
  - "hostvars[inventory_hostname]['unbound_download_root_hints'] == 'always'"
