---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['unbound_install_package'] is defined"
    - "hostvars[inventory_hostname]['unbound_install_package'] == 'true'"
- ansible.builtin.import_tasks:
    file: "deploy_root_hints.yml"
- ansible.builtin.import_tasks:
    file: "deploy_unbound.yml"
