---
- import_tasks: pre_requisite.yml
- include_tasks: packages.yml
  when:
  - "hostvars[inventory_hostname]['unbound_install_package'] is defined"
  - "hostvars[inventory_hostname]['unbound_install_package'] == 'true'"
- import_tasks: deploy_root_hints.yml
- import_tasks: deploy_unbound.yml
