---
- name: "unbound | Install the required packages in Redhat derivatives"
  ansible.builtin.dnf:
    name: "{{ hostvars[inventory_hostname]['unbound_package'] }}"
    state: "{{ vars['unbound_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
- name: "unbound | Install the required packages in Debian derivatives"
  ansible.builtin.apt:
    name: "{{ hostvars[inventory_hostname]['unbound_package'] }}"
    state: "{{ vars['unbound_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
- name: "unbound | Install the required packages in ArchLinux derivatives"
  community.general.pacman:
    name: "{{ hostvars[inventory_hostname]['unbound_package'] }}"
    state: "{{ vars['unbound_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
