---
- name: "unbound | Install the required packages in Redhat derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
  block:
    - name: "unbound | Update dnf cache"
      ansible.builtin.dnf:
        update_cache: "yes"
    - name: "unbound | Install package with dnf"
      ansible.builtin.dnf:
        name: "{{ hostvars[inventory_hostname]['unbound_package'] }}"
        state: "{{ vars['unbound_package_state'] | default(omit) }}"
- name: "unbound | Install the required packages in Debian derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
  block:
    - name: "unbound | Update apt cache"
      ansible.builtin.apt:
        update_cache: "yes"
    - name: "unbound | Install package with apt"
      ansible.builtin.apt:
        name: "{{ hostvars[inventory_hostname]['unbound_package'] }}"
        state: "{{ vars['unbound_package_state'] | default(omit) }}"
- name: "unbound | Install the required packages in ArchLinux derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
  block:
    - name: "unbound | Update pacman cache"
      community.general.pacman:
        update_cache: "yes"
    - name: "unbound | Install package with pacman"
      community.general.pacman:
        name: "{{ hostvars[inventory_hostname]['unbound_package'] }}"
        state: "{{ vars['unbound_package_state'] | default(omit) }}"
