---
- name: "Reload unbound daemon"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['unbound_service'] }}"
    state: "{{ vars['unbound_restart_cmd'] }}"
  when:
    - "hostvars[inventory_hostname]['unbound'] is defined"
    - "hostvars[inventory_hostname]['unbound'] != ''"
    - "hostvars[inventory_hostname]['unbound'] |
       json_query(vars['unbound_restart']) is defined"
    - "hostvars[inventory_hostname]['unbound'] |
       json_query(vars['unbound_restart']) == 'true'"
  vars:
    unbound_restart: "[] | map(&restart || 'false', @) | [0]"
